In [76]:
import numpy as np

def forwardAlgorithm(obs, a, b, pi):
    """
    :param obs: Observation Vector
    :param   a: Transition probability matrix
    :param   b: Output probability matrix
    :param  pi: Initial state probability vector
    :return: The Forward probability

    Instructions: Implement algorithm on slide 29 "The Forward Algorithm" of lecture note slides
    """
    # Tell Numpy how to print the array
    np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

    # Initialization step
    print('\033[1m' + 'Initialization' + '\033[0m')

    # Initialize alpha to zero using numpy zeros function
    alpha=np.zeros((obs.shape[0], a.shape[0]))

    alpha[0, :]= pi * b[:, obs[0]]
    print()
    print(alpha)
    print()

    # The Induction Step
    print('\033[1m' + 'Induction' + '\033[0m')
    for t in range(1, obs.shape[0]):
        for j in range(a.shape[0]):
            alphaSum=0.0
            for i in range(a.shape[0]):
                alphaSum+= alpha[t][j]
                alpha[t, j]=alpha[t - 1].dot(a[:, j]) * b[j, obs[t]]
            print("alpha(", t+1, ",", j+1, ")")

            print(alpha)
            print()
            #print(alphaSum)

    # The Termination Step
    print('\033[1m' + 'Termination' + '\033[0m')
    forwardProb = 0
    forwardProb = (alphaSum/2) + alpha[t][0] + alpha[t][1]
    return forwardProb

def main():
    # Observations
    # Note that 0 == H and 1 == T
    observationVector=np.array((0, 1, 1,1))

    # Transition Probabilities
    transitionProbMat=np.array(((0.4, 0.5, 0.1), (0.34, 0.16, 0.5), (0.15,0.4,0.55)))

    # Output Probabilities
    outputProbMat=np.array(((0.65, 0.35), (0.85, 0.15), (0.75,0.25)))

    # Initial state probability probability vector
    InitialStateProbVec=np.array((0.45, 0.25, 0.3))

    # Invoke the Forward algorithm
    forwardProb=forwardAlgorithm(observationVector, transitionProbMat, outputProbMat, InitialStateProbVec)

    print(f'P(O|\u03BB)={forwardProb:1.4f}')

if __name__ == "__main__":
    main()


Initialization

[[ 0.2925  0.2125  0.2250]
 [ 0.0000  0.0000  0.0000]
 [ 0.0000  0.0000  0.0000]
 [ 0.0000  0.0000  0.0000]]

Induction
alpha( 2 , 1 )
[[ 0.2925  0.2125  0.2250]
 [ 0.0781  0.0000  0.0000]
 [ 0.0000  0.0000  0.0000]
 [ 0.0000  0.0000  0.0000]]

alpha( 2 , 2 )
[[ 0.2925  0.2125  0.2250]
 [ 0.0781  0.0405  0.0000]
 [ 0.0000  0.0000  0.0000]
 [ 0.0000  0.0000  0.0000]]

alpha( 2 , 3 )
[[ 0.2925  0.2125  0.2250]
 [ 0.0781  0.0405  0.0648]
 [ 0.0000  0.0000  0.0000]
 [ 0.0000  0.0000  0.0000]]

alpha( 3 , 1 )
[[ 0.2925  0.2125  0.2250]
 [ 0.0781  0.0405  0.0648]
 [ 0.0192  0.0000  0.0000]
 [ 0.0000  0.0000  0.0000]]

alpha( 3 , 2 )
[[ 0.2925  0.2125  0.2250]
 [ 0.0781  0.0405  0.0648]
 [ 0.0192  0.0107  0.0000]
 [ 0.0000  0.0000  0.0000]]

alpha( 3 , 3 )
[[ 0.2925  0.2125  0.2250]
 [ 0.0781  0.0405  0.0648]
 [ 0.0192  0.0107  0.0159]
 [ 0.0000  0.0000  0.0000]]

alpha( 4 , 1 )
[[ 0.2925  0.2125  0.2250]
 [ 0.0781  0.0405  0.0648]
 [ 0.0192  0.0107  0.0159]
 [ 0.0048  0.0000 