In [4]:
"""
--------------------------------------------------------------------------
        Class: CS 582: Intro to Speech Processing
      Purpose: In this homework, you will implement the key HMM algorithms in Python
 Instructions:
     1. Write Python code as indicated
     2. Turn in this template with working code for each exercise.
     3. Turn in a sample run to demonstrate your work

        Title: Homework 2
          Due: 4.3.2021
         Name:
 Turn-in Date:
    File Name: HW2_VITERBI_Mineev_2323.py
--------------------------------------------------------------------------
Hint:
When correctly implemented for the example, your code should produce the following output:

Initialization
delta
[[ 0.7000  0.0000]
 [ 0.0000  0.0000]
 [ 0.0000  0.0000]]
psi
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Induction
Processed delta( 2 , 1 )
[[ 0.7000  0.0000]
 [ 0.0420  0.0000]
 [ 0.0000  0.0000]]
Processed psi( 2 , 1 )
[[0. 0.]
 [1. 0.]
 [0. 0.]]
Processed delta( 2 , 2 )
[[ 0.7000  0.0000]
 [ 0.0420  0.3360]
 [ 0.0000  0.0000]]
Processed psi( 2 , 2 )
[[0. 0.]
 [1. 1.]
 [0. 0.]]
Processed delta( 3 , 1 )
[[ 0.7000  0.0000]
 [ 0.0420  0.3360]
 [ 0.0605  0.0000]]
Processed psi( 3 , 1 )
[[0. 0.]
 [1. 1.]
 [2. 0.]]
Processed delta( 3 , 2 )
[[ 0.7000  0.0000]
 [ 0.0420  0.3360]
 [ 0.0605  0.0806]]
Processed psi( 3 , 2 )
[[0. 0.]
 [1. 1.]
 [2. 2.]]
Viterbi Score
0.08063999999999999
Best Path
[1 2 2]

"""

"""
     Class: CS 582 Intro To Speech Processing
      Name: C. Konopka
Homework 2: The Viterbi Algorithm
       Due: 04.03.21
"""

import numpy as np

# Tell Numpy how to print the array
np.set_printoptions(formatter={'float': '{: 0.4f}'.format})


def pathBacktrack(psi, bestPath):
    """
    :param psi: The path matrix
    :param bestPath: The best path
    """

    # T: The number of states in the best path
    T = bestPath.shape[0]

    for t in range(T-2, 0, -1):
        bestPath[t] = psi[t+1, bestPath[t+1]]


def viterbiAlgorithm(obs, pi, a, b):
    """
    :param obs: Observation Vector
    :param  pi: Initial state probability vector
    :param   a: Transition probability matrix
    :param   b: Output probability matrix
    :return: The Viterbi score
    :return: The best path
    """

    # T The number of observations
    T = obs.shape[0]

    # N The number of states in the model
    N = a.shape[0]

    # psi = the path matrix
    # rows = number of observations
    # cols = number of states
    psi = np.zeros((T, N))
    psi.fill(-1.0)
    # delta = Tracks induction step progress
    # rows = number of observations
    # cols = number of states
    delta = np.zeros((T, N))

    # The best path
    bestPath = np.zeros(T, dtype=int)

    # Initialize viterbiScore to zero using numpy zeros function
    viterbiScore = 0.0

    # Initialization step
    delta[0, :] = pi * b[ obs[0], :]
    print()
    print('\033[1m' + 'Initialization' + '\033[0m')
    print('\033[1m' + 'delta' + '\033[0m')
    print(delta)
    print('\033[1m' + 'psi' + '\033[0m')
    np.set_printoptions()
    print(psi + 1)
    print()

    # The Induction Step
    # currentRow used in induction step
    currentRow = np.zeros(N)

    print('\033[1m' + 'Induction' + '\033[0m')
    for t in range(1, T):
        for deltaColIdx in range(N):
            currentRow.fill(0)
            for currColIdx in range(N):
                currentRow[currColIdx]=delta[t-1][currColIdx]*a[currColIdx][deltaColIdx]

            currMax = np.amax(currentRow)
            delta[t, deltaColIdx]= currMax*b[obs[t],deltaColIdx]
            psi[t, deltaColIdx] = np.argmax(currentRow)

            print("Processed delta(", t+1, ",", deltaColIdx+1, ")")
            np.set_printoptions(formatter={'float': '{: 0.10f}'.format})
            print(delta)
            print("Processed psi(", t+1, ",", deltaColIdx+1, ")")
            np.set_printoptions()
            print(psi + 1)
            print()

    # Termination Step
    lastRow = delta[T-1]
    viterbiScore = np.max(delta[T-1])
    bestPath[T-1] = np.argmax(delta[T-1])
    pathBacktrack(psi, bestPath)

    return viterbiScore, bestPath


def main():
    # Observations
    observationVector = np.array((0, 1, 1))

    # Initial state probability probability vector
    InitialStateProbVec=np.array((1.0, 0.0))

    # Transition Probabilities
    transitionProbMat=np.array(((0.2, 0.8), (0.6, 0.4)))

    # Output Probabilities
    outputProbMat=np.array(((0.7, 0.4), (0.3, 0.6)))

    # Invoke the Forward algorithm
    viterbiScore, bestPath = viterbiAlgorithm(observationVector, InitialStateProbVec, transitionProbMat, outputProbMat)

    print(f'\033[1m'+'Viterbi Score' + '\033[0m')
    print(viterbiScore)
    print('\033[1m' + 'Best Path' + '\033[0m')
    np.set_printoptions()

    # Print best path. Note that 0-based index is converted to 1-based state numbers.
    print(bestPath + 1)


if __name__ == "__main__":
    main()



Initialization
delta
[[ 0.7000  0.0000]
 [ 0.0000  0.0000]
 [ 0.0000  0.0000]]
psi
[[0. 0.]
 [0. 0.]
 [0. 0.]]

Induction
Processed delta( 2 , 1 )
[[ 0.7000000000  0.0000000000]
 [ 0.0420000000  0.0000000000]
 [ 0.0000000000  0.0000000000]]
Processed psi( 2 , 1 )
[[0. 0.]
 [1. 0.]
 [0. 0.]]

Processed delta( 2 , 2 )
[[ 0.7000000000  0.0000000000]
 [ 0.0420000000  0.3360000000]
 [ 0.0000000000  0.0000000000]]
Processed psi( 2 , 2 )
[[0. 0.]
 [1. 1.]
 [0. 0.]]

Processed delta( 3 , 1 )
[[ 0.7000000000  0.0000000000]
 [ 0.0420000000  0.3360000000]
 [ 0.0604800000  0.0000000000]]
Processed psi( 3 , 1 )
[[0. 0.]
 [1. 1.]
 [2. 0.]]

Processed delta( 3 , 2 )
[[ 0.7000000000  0.0000000000]
 [ 0.0420000000  0.3360000000]
 [ 0.0604800000  0.0806400000]]
Processed psi( 3 , 2 )
[[0. 0.]
 [1. 1.]
 [2. 2.]]

Viterbi Score
0.08063999999999999
Best Path
[1 2 2]
